# Generated by Django 4.2.7 on 2023-11-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField()),
                ('author', models.CharField()),
                ('featured_image', models.CharField()),
                ('published_datetime', models.DateTimeField()),
                ('summary', models.CharField()),
                ('body', models.TextField()),
            ],
        ),
    ]
