# Generated by Django 4.2.7 on 2023-11-18 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='headline',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(limit_value=1, message='Headline cannot be empty')]),
        ),
    ]
