# Generated by Django 4.2.7 on 2023-11-18 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(limit_value=1, message='Author cannot be empty')]),
        ),
    ]
