# Generated by Django 4.2.7 on 2023-12-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blogpost_check_required_fields_non_empty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.CharField(null=True),
        ),
    ]
