# Generated by Django 4.2.7 on 2023-12-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpost_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='summary',
            field=models.CharField(null=True),
        ),
    ]
