# Generated by Django 4.2.7 on 2023-12-14 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogpost_body_alter_blogpost_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
