# Generated by Django 4.2.7 on 2023-12-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blogpost_published_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published_datetime',
            field=models.DateTimeField(),
        ),
    ]
