# Generated by Django 4.2.7 on 2023-12-14 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_blogpost_published_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='modified_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
