# Generated by Django 4.2.7 on 2023-12-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogpost_modified_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='modified_datetime',
            field=models.DateTimeField(),
        ),
    ]
