# Generated by Django 4.2.7 on 2023-12-15 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_blogpost_modified_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='modified_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
