# Generated by Django 4.2.7 on 2023-12-15 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_blogpost_modified_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='modified_datetime',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
