# Generated by Django 4.2.7 on 2023-12-15 04:35

import blog.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_blogpost_modified_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='headline',
            field=models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(limit_value=1, message='Headline cannot be empty')]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='modified_datetime',
            field=models.DateTimeField(default=blog.utils.now),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_datetime',
            field=models.DateTimeField(default=blog.utils.now),
        ),
    ]
