# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 20:38
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='Published')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('excerpt', models.TextField()),
                ('heading_image', models.ImageField(default='', max_length=200, upload_to='blog/')),
            ],
        ),
    ]
